name: Alexandria
authors: [Cleopatra_Vll]
version: 0.1
main: org.alexdev.alexandria.Alexandria
api-version: 1.20
folia-supported: true

commands:
  chunkage:
    description: gets the age of the chunk in Minecraft ticks and hours/seconds
    permission: alexandria.use
  setchatcolour:
    aliases:
      - setchatcolor
    description: decorates your display name in chat
    usage: |
      /setchatcolour [colour]
    permission: alexandria.chat

  banish:
    description: Teleports you safely somewhere randomly in the world.
    usage: |
      /banish
    permission: alexandria.use

  afk:
    description: Sets you to AFK status and will untoggle AFK immediately if you start moving.
    usage: |
      /afk
    permission: alexandria.use

  tprequest:
    description: Sends a teleport request to somebody
    aliases:
      - tpr
    permission: alexandria.use
    permission-message: You do not have permission!
    usage: /<command> [target]

  tpaccept:
    description: Accepts a teleport request
    aliases:
      - tpa
    permission: alexandria.use
    permission-message: You do not have permission!
    usage: /<command>

  tpdecline:
    description: Declines a teleport request
    aliases:
      - tpa
    permission: alexandria.use
    permission-message: You do not have permission!
    usage: /<command>

permissions:
  alexandria.use:
    description: use alexandria
    default: true
  alexandria.chat:
    description: use alexandria chat decoration command
    default: true