name: Alexandria
authors: [Cleopatra_Vll]
version: 0.1
main: org.alexdev.alexandria.Alexandria
api-version: 1.20

commands:
  banish:
    description: Teleports you safetly somewhere randomly in te world.
    aliases: [ctf]
    usage: |
      /ctf [arguments]
    permission: alexandria.use

  tprequest:
    description: Sends a teleport request to somebody
    aliases:
      - tpr
    permission: alexandria.use
    permission-message: You do not have permission!
    usage: /<command> [target]

  tpaccept:
    description: Accepts a teleport request
    aliases:
      - tpa
    permission: alexandria.use
    permission-message: You do not have permission!
    usage: /<command>

  tpdecline:
    description: Declines a teleport request
    aliases:
      - tpa
    permission: alexandria.use
    permission-message: You do not have permission!
    usage: /<command>

permissions:
  alexandria.use:
    description: use alexandria
    default: true